services:
  godev-server:
    build:
      context: ./docker
      dockerfile: Dockerfile
    image: docker.io/junhajo/godev-server:${GO_VERSION}
    container_name: godev-server
    hostname: godev-server-ubuntu-22045
    volumes:
      - ~/container/godev-server/home:/home
      - ~/container/godev-server/go:/go
    ports:
      - "${HOST_PORT}:22"
    restart: always
    environment:
      - TZ=Asia/Seoul
    networks:
      bridge-network:
        aliases:
          - godev
    depends_on:
      - godev-mongodb
      - godev-redis

  godev-mongodb:
    container_name: godev-mongodb
    image: mongo:4.4
    command: mongod --port ${MONGODB_PORT}
    expose:
      - "${MONGODB_PORT}"
    volumes:
      - ~/container/mongodb/data/db:/data/db
    restart: always
    networks:
      bridge-network:
        aliases:
          - mongodb

  godev-redis:
    container_name: godev-redis
    image: redis:7.2-alpine
    command: redis-server --port ${REDIS_PORT}
    expose:
      - "${REDIS_PORT}"
    volumes:
      - ~/container/redis/data:/data
    restart: always
    networks:
      bridge-network:
        aliases:
          - redis

networks:
  bridge-network:
    ipam:
      driver: default
      config:
        - subnet: 10.100.200.0/24
    driver_opts:
      com.docker.network.bridge.name: godev-bridge
